<script lang="ts">
	import { getContext } from 'svelte';
	import Modal from '$lib/components/common/Modal.svelte';

	const i18n = getContext('i18n');

	export let sources: any[] = [];
	export let content = '';

	type NormalizedCitation = {
		citation_index: number;
		title: string;
		source?: string;
		score?: number;
		aliases: string[];
	};

	let showCitationModal = false;
	let selectedCitationIndex: number | null = null;
	let sortedSources: NormalizedCitation[] = [];
	let displayedSources: NormalizedCitation[] = [];
	let modalSources: NormalizedCitation[] = [];

	function asNonEmptyString(value: any) {
		return typeof value === 'string' && value.trim() !== '' ? value.trim() : null;
	}

	function extractUsedCitationTokens(text: string) {
		const used = new Set<string>();
		if (!text || typeof text !== 'string') return used;

		const bracketRegex = /\[([^\]]+)\]/g;
		let match: RegExpExecArray | null = null;
		while ((match = bracketRegex.exec(text)) !== null) {
			const raw = match[1] ?? '';
			raw
				.split(/[,\uFF0C]/)
				.map((part) => part.trim())
				.filter((part) => part.length > 0)
				.forEach((part) => used.add(part));
		}

		return used;
	}

	$: {
		const next: NormalizedCitation[] = [];

		// New format: citation_index already generated by backend.
		const indexed = (sources ?? []).filter(
			(item) => item && item.citation_index !== undefined && item.citation_index !== null
		);
		if (indexed.length > 0) {
			for (const item of indexed) {
				const aliases = new Set<string>();
				aliases.add(String(item.citation_index));

				const sourceAlias = asNonEmptyString(item.source);
				if (sourceAlias) aliases.add(sourceAlias);

				const referenceAlias = asNonEmptyString(
					item.reference_id ?? item.referenceId ?? item.metadata?.reference_id ?? item.metadata?.referenceId
				);
				if (referenceAlias) aliases.add(referenceAlias);

				const titleAlias = asNonEmptyString(item.title);
				if (titleAlias) aliases.add(titleAlias);

				next.push({
					citation_index: Number(item.citation_index),
					title: item.title ?? item.source ?? 'Unknown source',
					source: item.source,
					score: item.score,
					aliases: Array.from(aliases)
				});
			}
			sortedSources = next.sort((a, b) => (a.citation_index ?? 9999) - (b.citation_index ?? 9999));
		} else {
			// Legacy format fallback: derive citation_index deterministically on frontend.
			const map = new Map<string, NormalizedCitation>();
			for (const source of sources ?? []) {
				if (!source || !Array.isArray(source.document)) continue;

				source.document.forEach((_doc: any, index: number) => {
					const metadata = source.metadata?.[index] ?? {};
					const title =
						metadata?.title ?? metadata?.name ?? source?.source?.name ?? metadata?.source ?? 'Unknown source';
					const key = title;
					const distance = source?.distances?.[index];

					const aliasCandidates = [
						metadata?.reference_id,
						metadata?.referenceId,
						metadata?.source,
						metadata?.name,
						metadata?.title,
						source?.source?.name
					]
						.map(asNonEmptyString)
						.filter(Boolean) as string[];

					if (!map.has(key)) {
						map.set(key, {
							citation_index: 0,
							title,
							source: metadata?.source ?? source?.source?.name,
							score: distance,
							aliases: aliasCandidates
						});
						return;
					}

					const existing = map.get(key);
					if (!existing) return;
					existing.aliases = Array.from(new Set([...existing.aliases, ...aliasCandidates]));
				});
			}

			let idx = 1;
			for (const item of map.values()) {
				item.citation_index = idx++;
				item.aliases = Array.from(new Set([String(item.citation_index), ...item.aliases]));
				next.push(item);
			}

			sortedSources = next.sort((a, b) => (a.citation_index ?? 9999) - (b.citation_index ?? 9999));
		}
	}

	$: {
		const usedTokens = extractUsedCitationTokens(content);
		if (usedTokens.size === 0) {
			displayedSources = [];
		} else {
			displayedSources = sortedSources.filter((source) => {
				if (usedTokens.has(String(source.citation_index))) return true;
				return source.aliases.some((alias) => usedTokens.has(alias));
			});
		}
	}

	$: modalSources =
		selectedCitationIndex !== null
			? sortedSources.filter((source) => source.citation_index === selectedCitationIndex)
			: displayedSources;

  $: console.log('[Citations debug]', {
    sources,
    sourcesLength: sources?.length,
    contentPreview: content?.slice?.(0, 300),
    sortedSources,
    displayedSources
  });
</script>

{#if sortedSources.length > 0}
	<!-- Keep hidden anchors so inline [n] clicks can open the citation modal. -->
	<div class="hidden">
		{#each sortedSources as source}
			{#each source.aliases as alias}
				<button
					id={`source-${alias}`}
					data-citation-index={source.citation_index}
					type="button"
					on:click={() => {
						selectedCitationIndex = source.citation_index;
						showCitationModal = true;
					}}
				>
					[{source.citation_index}] {source.title}
				</button>
			{/each}
		{/each}
	</div>
{/if}

{#if displayedSources.length > 0}
	<div class="py-0.5 -mx-0.5 w-full flex gap-1 items-center flex-wrap">
		<button
			type="button"
			class="no-toggle outline-none flex items-center gap-1 text-xs font-medium text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 transition bg-gray-50 hover:bg-gray-100 dark:bg-gray-900 dark:hover:bg-gray-850 rounded-xl px-2 py-1"
			on:click={() => {
				selectedCitationIndex = null;
				showCitationModal = true;
			}}
		>
			{$i18n.t('Citation')}
			<span class="text-gray-400">({displayedSources.length})</span>
		</button>
	</div>
{/if}

<Modal size="md" bind:show={showCitationModal}>
	<div class="flex items-center justify-between px-5 pt-4 pb-2">
		<div class="text-lg font-medium dark:text-gray-200">{$i18n.t('Citation')}</div>
		<button
			type="button"
			class="text-gray-500 hover:text-gray-800 dark:hover:text-gray-200 transition"
			on:click={() => {
				showCitationModal = false;
			}}
		>
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
				<path
					d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
				/>
			</svg>
		</button>
	</div>

	<div class="px-5 pb-5 max-h-[60vh] overflow-y-auto">
		<div class="flex flex-col gap-2 text-sm">
			{#each modalSources as source}
				<div class="flex gap-2 text-gray-800 dark:text-gray-200">
					<div class="shrink-0 text-gray-500">[{source.citation_index}]</div>
					<div class="break-words">{source.title}</div>
				</div>
			{/each}
		</div>
	</div>
</Modal>
